
services:
  dynamic_mesh_gen:

    build: 
      context: ${HOST_WORKSPACE_FOLDER:-/CHANGEMEws}
      args:
        DYNAMIC_MESH_TARGET_WORKSPACE: "/CHANGEME_ws"
        DYNAMIC_MESH_SRC_SUBDIR: "src/dynamic_mesh"
      dockerfile: ${HOST_WORKSPACE_FOLDER}/${DYNAMIC_MESH_SRC_SUBDIR}/container/docker_compose/build.Dockerfile

    image: erf2025.demo/dynamic_mesh_c
    container_name: dynamic_mesh_gen_c
    # entrypoint: tail -f /dev/null
    entrypoint: ${DYNAMIC_MESH_SRC_SUBDIR}/container/docker_compose/scripts/run_app.sh -t ${DYNAMIC_MESH_SRC_SUBDIR}

    environment:
      DEV_WORKSPACE: ${DYNAMIC_MESH_TARGET_WS:-/workspaces/mesh_ws}
      CACHED_DEV_WORKSPACE: ${DYNAMIC_MESH_SRC_SUBDIR}

    env_file:
      - path: variables.env
        required: true # default

    network_mode: host

    working_dir: ${DYNAMIC_MESH_SRC_SUBDIR:-/workspaces/mesh_ws}

    user: ${PUID:-1000}:${PGID:-1000}

    ipc: host

    mem_limit: 12gb # TODO confirm this

    privileged: true

    tty: true
